--- #YAML:1.0
name:                PerlPoint-Package
version:             0.452
abstract:            A framework to write PerlPoint converters.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Digest::SHA1:                  1
    File::Spec:                    0.8
    File::Temp:                    0.12
    Getopt::Long:                  2.24
    IO::File:                      1
    Pod::Simple:                   3.02
    Storable:                      1
    Test::Harness:                 1.25
    Test::More:                    0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
